#pragma once

// From GLFW
#define NEATO_MOUSE_BUTTON_1         0
#define NEATO_MOUSE_BUTTON_2         1
#define NEATO_MOUSE_BUTTON_3         2
#define NEATO_MOUSE_BUTTON_4         3
#define NEATO_MOUSE_BUTTON_5         4
#define NEATO_MOUSE_BUTTON_6         5
#define NEATO_MOUSE_BUTTON_7         6
#define NEATO_MOUSE_BUTTON_8         7
#define NEATO_MOUSE_BUTTON_LAST      NEATO_MOUSE_BUTTON_8
#define NEATO_MOUSE_BUTTON_LEFT      NEATO_MOUSE_BUTTON_1
#define NEATO_MOUSE_BUTTON_RIGHT     NEATO_MOUSE_BUTTON_2
#define NEATO_MOUSE_BUTTON_MIDDLE    NEATO_MOUSE_BUTTON_3